#!/bin/sh

configure_github_help() {
  echo "Configure local git identity and GitHub credentials"
}

configure_github() {
  GIT_NAME="$1"
  GIT_EMAIL="$2"
  PERSONAL_ACCESS_TOKEN="$3"

  git config --local user.name "$GIT_NAME"
  git config --local user.email "$GIT_EMAIL"
  git config --local \
    url."https://$PERSONAL_ACCESS_TOKEN:@github.com/".insteadOf "https://github.com/"
}
