#!/bin/sh

. "$KANO_HELPERS/fail"

DEFAULT_UBUNTU_VERSION="22.04"

release_help() {
  echo "Build and release images to registry"
}

release() {
  REGISTRY="$1"
  HELOT_VERSION="$2"

  if [ -z "$REGISTRY" ]; then
    _fail "No registry url provided"
  fi

  if [ -z "$HELOT_VERSION" ]; then
    _fail "No helot version provided"
  fi

  for UBUNTU_VERSION in $(_get_ubuntu_versions); do
    _build_and_release_image "$REGISTRY" "$HELOT_VERSION" "$UBUNTU_VERSION"
  done
}

_get_ubuntu_versions() {
  echo "22.04"
  echo "20.04"
}

_build_and_release_image() {
  REGISTRY="$1"
  HELOT_VERSION="$2"
  UBUNTU_VERSION="$3"

  # shellcheck disable=SC2046
  docker buildx build \
    --file .kano/Dockerfile \
    --build-arg UBUNTU_VERSION="$UBUNTU_VERSION" \
    --platform linux/amd64,linux/arm64 \
    $(_get_tag_arguments "$REGISTRY" "$HELOT_VERSION" "$UBUNTU_VERSION") \
    --push \
    --cache-to=type=inline \
    --label "org.opencontainers.image.title=helot-$UBUNTU_VERSION" \
    --label "org.opencontainers.image.description=logisparte's base development image" \
    --label "org.opencontainers.image.authors=@logisparte" \
    --label "org.opencontainers.image.source=https://github.com/logisparte/helot" \
    --label "org.opencontainers.image.base.name=ubuntu:$UBUNTU_VERSION" \
    .
}

_get_tag_arguments() {
  REGISTRY="$1"
  HELOT_VERSION="$2"
  UBUNTU_VERSION="$3"

  BASE_NAME="$REGISTRY/helot"
  echo "--tag $BASE_NAME-$UBUNTU_VERSION:$HELOT_VERSION"
  echo "--tag $BASE_NAME-$UBUNTU_VERSION:latest"
  if [ "$UBUNTU_VERSION" = "$DEFAULT_UBUNTU_VERSION" ]; then
    echo "--tag $BASE_NAME:$HELOT_VERSION"
    echo "--tag $BASE_NAME:latest"
  fi
}

_fail() {
  MESSAGE="$1"

  fail "[release] $MESSAGE"
}
