#!/bin/sh

. "$KANO_HELPERS/fail"

DEFAULT_UBUNTU_VERSION="20.04"

release_help() {
  echo "Build and release helot images to registry"
}

release() {
  REGISTRY="$1"
  REPOSITORY="$2"
  HELOT_VERSION="$3"

  if [ -z "$REGISTRY" ]; then
    fail "No registry url provided"
  fi

  if [ -z "$REPOSITORY" ]; then
    fail "No registry repository name provided"
  fi

  if [ -z "$HELOT_VERSION" ]; then
    fail "No helot version provided"
  fi

  BASE_NAME="$REGISTRY/$REPOSITORY"

  for UBUNTU_VERSION in $(_get_ubuntu_versions); do
    _build_and_release_image "$BASE_NAME" "$HELOT_VERSION" "$UBUNTU_VERSION"
  done
}

_get_ubuntu_versions() {
  echo "16.04"
  echo "18.04"
  echo "20.04"
}

_build_and_release_image() {
  BASE_NAME="$1"
  HELOT_VERSION="$2"
  UBUNTU_VERSION="$3"

  # shellcheck disable=SC2046
  docker buildx build \
    --file .kano/Dockerfile \
    --build-arg UBUNTU_VERSION="$UBUNTU_VERSION" \
    --platform linux/amd64,linux/arm64 \
    $(_get_tag_arguments "$BASE_NAME" "$HELOT_VERSION" "$UBUNTU_VERSION") \
    --push \
    --label "org.opencontainers.image.title=helot-$UBUNTU_VERSION" \
    --label "org.opencontainers.image.description=logisparte's base development image" \
    --label "org.opencontainers.image.authors=@logisparte" \
    --label "org.opencontainers.image.source=https://github.com/logisparte/helot" \
    --label "org.opencontainers.image.base.name=ubuntu:$UBUNTU_VERSION" \
    .
}

_get_tag_arguments() {
  BASE_NAME="$1"
  HELOT_VERSION="$2"
  UBUNTU_VERSION="$3"

  QUALIFIED_NAME="$BASE_NAME-$UBUNTU_VERSION"

  echo "--tag $QUALIFIED_NAME:$HELOT_VERSION"
  echo "--tag $QUALIFIED_NAME:latest"

  if [ "$UBUNTU_VERSION" = "$DEFAULT_UBUNTU_VERSION" ]; then
    echo "--tag $BASE_NAME:$HELOT_VERSION"
    echo "--tag $BASE_NAME:latest"
  fi
}
