#!/bin/sh

. "$KANO_HELPERS/fail"
. "$KANO_HELPERS/report"

test_help() {
  echo "Test the development environment"
}

test() {
  _test_github
  _test_aws
  report success "[test] Tests passed"
}

_test_github() {
  gh --version >/dev/null 2>&1 || _fail "GitHub not properly installed"
}

_test_aws() {
  aws --version >/dev/null 2>&1 || _fail "AWS not properly installed"
}

_fail() {
  MESSAGE="$1"

  fail "[test] $MESSAGE"
}