#!/bin/sh -e

install_aws() {
  TARGETARCH="$1"

  VERSION="2.7.7"
  case "$TARGETARCH" in
    amd64)
      PACKAGE_ARCHITECTURE="x86_64"
      ;;

    arm64*)
      PACKAGE_ARCHITECTURE="aarch64"
      ;;

    *)
      echo "Unknown architecture $TARGETARCH" >&2
      exit 1
      ;;
  esac

  curl -o awscliv2.zip "https://awscli.amazonaws.com/awscli-exe-linux-$PACKAGE_ARCHITECTURE-$VERSION.zip"
  unzip awscliv2.zip
  rm -rf awscliv2.zip
  ./aws/install
  rm -rf ./aws
}

install_aws "$@"
