name: cd

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

env:
  REGISTRY: ghcr.io
  HELOT_GITHUB_USERNAME: logisparte-helot
  HELOT_GITHUB_ACCESS_TOKEN: ${{ secrets.HELOT_GITHUB_ACCESS_TOKEN }}
  REPOSITORY: ${{ github.repository }}
  GITHUB_REF: ${{ github.ref }}
  DOCKER_BUILDKIT: true

jobs:
  run_cd:
    runs-on: ubuntu-latest
    steps:
      - name: Install kano
        run: |
          curl -L https://github.com/logisparte/kano/releases/download/3.5.3/kano.tar.gz \
            | tar -xz
          sudo ./kano/install

      - name: Export environment variable
        run: |
          VERSION="$(echo "$GITHUB_REF" | cut -d "/" -f 3)"
          echo "VERSION=$VERSION" >> "$GITHUB_ENV"

      - name: Clone project
        uses: actions/checkout@v2

      - name: Login to registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.HELOT_GITHUB_USERNAME }}
          password: ${{ env.HELOT_GITHUB_ACCESS_TOKEN }}

      - name: Setup QEMU multi-architecture emulators
        uses: docker/setup-qemu-action@v2
        with:
          platforms: amd64,arm64

      - name: Setup buildx multi-architecture builder
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker-container

      - name: Build and release images
        run: kano release "$REGISTRY" "$REPOSITORY" "$VERSION"
