name: CD

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

env:
  REGISTRY_URL: ghcr.io
  HELOT_GITHUB_USERNAME: logisparte-helot
  HELOT_GITHUB_ACCESS_TOKEN: ${{ secrets.HELOT_GITHUB_ACCESS_TOKEN }}
  REPOSITORY: ${{ github.repository }}
  GITHUB_REF: ${{ github.ref }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Export variables
        run: |
          IMAGE="$REGISTRY_URL/$REPOSITORY"
          VERSION="$(echo "$GITHUB_REF" | cut -d "/" -f 3)"
          echo "VERSIONED_IMAGE=$IMAGE:$VERSION" >> "$GITHUB_ENV"
          echo "LATEST_IMAGE=$IMAGE:latest" >> "$GITHUB_ENV"

      - name: Clone
        uses: actions/checkout@v2

      - name: Build image
        run: |
          docker build \
            --tag "$VERSIONED_IMAGE" \
            --tag "$LATEST_IMAGE" \
            ./docker

      - name: Login to registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY_URL }}
          username: ${{ env.HELOT_GITHUB_USERNAME }}
          password: ${{ env.HELOT_GITHUB_ACCESS_TOKEN }}

      - name: Push image to registry
        run: |
          docker push "$VERSIONED_IMAGE"
          docker push "$LATEST_IMAGE"
