name: cd

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

env:
  DOCKER_BUILDKIT: true
  DOCKER_REGISTRY: ghcr.io
  DOCKER_USERNAME: logisparte-helot
  DOCKER_PASSWORD: ${{ secrets.HELOT_GITHUB_ACCESS_TOKEN }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Install kano
        run: |
          curl -L https://github.com/logisparte/kano/releases/download/3.6.0/kano.tar.gz \
            | tar -xz
          sudo ./kano/install

      - name: Clone project
        uses: actions/checkout@v2

      - name: Login to registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Setup QEMU multi-architecture emulators
        uses: docker/setup-qemu-action@v2
        with:
          platforms: amd64,arm64

      - name: Setup buildx multi-architecture builder
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker-container

      - name: Build and release images
        run: kano release "$DOCKER_REGISTRY" "$GITHUB_REPOSITORY" "$GITHUB_REF_NAME"
